//
//  StorageManager.swift
//  LanguageClasses
//
//  Created by Бойко Григорий on 07/06/2020.
//  Copyright © 2020 Бойко Григорий. All rights reserved.
//

import RealmSwift

//Сама базы данных
let realm = try! Realm()

class StorageManager {
    
    static func saveObject(_ obj: Object) {
        try! realm.write {
            realm.add(obj)
        }
    }
    
    static func deleteObject(_ obj: Object){
        try! realm.write {
            realm.delete(obj)
        }
    }
    
    static func testFillArticles(){
        let text = Text("Realm Swift 5.2.0", """
        Prerequisites
        XCode 10.0 or higher
        Target of iOS 9 or higher, macOS 10.9 or higher, or any version of tvOS or watchOS

        Install CocoaPods 1.6.0 or later.
        Run pod repo update to make CocoaPods aware of the latest available Realm versions.
        In your Podfile, add use_frameworks! and pod 'RealmSwift' to your main and test targets.
        From the command line, run pod install.
        Use the .xcworkspace file generated by CocoaPods to work on your project!

        If you’re looking to use Realm from Objective‑C, or from mixed Objective‑C & Swift apps, please see Realm Objective‑C instead. The Realm Objective‑C and Realm Swift APIs are not interoperable and using them together is not supported.

        Realm Swift enables you to efficiently write your app’s model layer in a safe, persisted and fast way. Here’s what it looks like:
        """)
        StorageManager.saveObject(text)
    }
}
